### ISSUE TITLE
What about using composer.json ? 

### ISSUE THREAD

**Issue by fpiccinali** [crazy-max/CwsMailBounceHandler#11]
et si on mettait en place un composer.json. 

Composer facilite la mise en place et les mises à jour. Il automatise les mises à jour et gère les dépendances. 

Je vais proposer une pull request dans ce sens.  

@crazy-max : que penses-tu de découpler la classe principale de ses dépendancs avec les class de debug et de dump ? On aurait ainsi une class autonome et chacun pourrait utiliser son débuggeur préféré. Je penses en particulier lors d' une intégration dans symfony.

**Comment by crazy-max** [comment]
Yes j'aurais préféré utiliser composer mais pas le temps de mettre ça en place.
Si t'es motivé j'veux bien :)
Et pourquoi pas mettre ça sur packagist.

**Comment by fpiccinali** [comment]
je viens de faire un composer qui fonctionne

je vais faire une pull request dans 5 min. 

Il faudrait que tu te créé un compte sur packagist et que tu déclare le projet. Je viens de le faire pour tester et ça prend 3 minutes. Il ne faudra pas oublier d'activer le webhook dans github pour que les push soient mis à jour. 

Il serait jolie de faire un fichier par classes et de les nommer selon la convention PSR qui va bien. 
Pour être compatible on pourrait faire des  fichiers : 
CwsMailBounceHandler.php
CwsMbhCounter.php
CwsMbhMail.php
CwsMbhRecipient.php 
CwsMbhResult.php

et dans class.cws.mbh.php on met une rafale d'include.

ainsi l'ancienne manière continuerait de fonctionner et on aurait l'organisation "à la mode" 

On pourrait aussi se fendre d'un namespace crazy-max/*

Si ça te conviens, donne moi ton feu vert et je peux m'en charger.

**Comment by crazy-max** [comment]
Ok j'ai mergé ton PR et j'avais déjà un compte Packagist mais aucun package mis en place c'est fait maintenant : https://packagist.org/packages/crazy-max/cws-mail-bounce-handler

Sinon oui en effet il faudrait restructurer le projet pour respecter la conv PSR.
Je préférerais plutôt une structure du type tree (Cws/MailBounceHandler/Models/Mail.php, etc...)
Alors oui pour les namespaces et vu qu'il y a un seul service on pourra pour l'instant oublier l'injection de deps bien que plus tard je pourrais refondre cwsDebug et cwsDump (ou bien intégrer Monolog et le varDumper de Symfony comme tu dis par exemple).

A voir donc en tout cas merci pour ta contribution :)
