### ISSUE TITLE
No way to get mail content and headers?

### ISSUE THREAD

**Issue by malas** [crazy-max/CwsMailBounceHandler#17]
After `Handler->processMails()` i did not find any way to get mail headers or content.

This would be very handy when the processed mail has `Handler::CAT_UNKNOWN` or `Handler::CAT_UNRECOGNIZED`. We could save the bounced email to DB (or any other source) and later examine it by hand and mark it as soft/hard bounce or to enhance the process and declare new rules.

Is there any way to get the same results without extending your classes? And would you be interested in such Pull request?

**Comment by crazy-max** [comment]
Hi,

Yes indeed the process does not return the content or headers of mails.
You want you can create a new PR if you want :)

**Comment by crazy-max** [comment]
Fixed.
Now the Mail object contains the vars header and body.
