### ISSUE TITLE
MAILBOX_PORT_TLS_SSL 995?

### ISSUE THREAD

**Issue by ickbinhier** [crazy-max/CwsMailBounceHandler#20]
is MAILBOX_PORT_TLS_SSL realy Port 995? This is the SSL Port for POP3. Or?

In my Imap Server from the Uni is this Port 993. 

Can We make a split into IMAP and POP3 constante?

https://github.com/crazy-max/CwsMailBounceHandler/blob/master/lib/Cws/MailBounceHandler/Handler.php#L33

**Comment by crazy-max** [comment]
Indeed for it's the pop3 SSL/TLS port
We can split the IMAP and POP3 like you said

**Comment by crazy-max** [comment]
Fixed
