### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by ickbinhier** [crazy-max/CwsMailBounceHandler#22]
1. It is wanted that mails which are not a delivery notification are not deleted even though DeleteProcessMode is set to on.

2. I would like to use the NeutralProcessMode and delete the mails if necessary and depending on the situation by hand. Is that possible?

**Comment by ickbinhier** [comment]
@crazy-max to 2.
Can we modify the processMailDelete and processMailMove functions in the class handler to public? Then, although you are in neutral mode, you would have to delete or delete individual mail. Am I seeing this right?

**Comment by crazy-max** [comment]
Hi @ickbinhier!

Sorry i don't saw your issue
Yes it would be possible but i have to  evaluate this.
If you want, reopen this issue.
Thanks

**Comment by crazy-max** [comment]
Solved in 1.11
