### ISSUE TITLE
Problem with Yahoo

### ISSUE THREAD

**Issue by ickbinhier** [crazy-max/CwsMailBounceHandler#27]
Hello,

@crazy-max 

i have added a zip file with a eml inside.

This mail is not correctly recognized as bounce mail.

Can you please check this an fix the code.

[Delivery failure.eml.zip](https://github.com/crazy-max/CwsMailBounceHandler/files/1172860/Delivery.failure.eml.zip)

**Comment by crazy-max** [comment]
Hi @ickbinhier,

Of course, i'll keep you informed.

**Comment by crazy-max** [comment]
Solved in 1.12

**Comment by ickbinhier** [comment]
thankyou
