### ISSUE TITLE
Malformed email can lead to warnings

### ISSUE THREAD

**Issue by timothy-burnside** [crazy-max/CwsMailBounceHandler#28]
In MailBounceHandler\Handler:

parseDsnFields() can return null for the 'perRecipient' element of the result array.

This ends in a warning in parseBodySectionMachine() on line 877 because 'perRecipient' is not an array.

**Comment by crazy-max** [comment]
Thanks for your contrib i will take a look

**Comment by crazy-max** [comment]
Solved in latest release (1.13)
